### ISSUE TITLE
模板化二级分类和商品展示

### ISSUE THREAD

**Issue by linhandev** [thundersword/fire-shop-lite#11]
使用过程中很多甲方实际上没有很多商品，二级分类的地方希望能够直接展示具体的商品。如果将二级分类列表和商品展示都模板化能够实现很灵活的切换，而且定制开发的时候也能很方便的调用。

**Comment by thundersword** [comment]
此功能已增加，可以通过categoryLevel （文本参数）控制

**Comment by linhandev** [comment]
6得很
